name: assemble

on:
  push:
    branches:
      - main
    path:
      - '**'
    pull_request:
      branches:
        - main
      path:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-versions: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint 
